remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Sandro TEIXEIRA
description: Développeur & Futur Formateur
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
